### ISSUE TITLE
Key for iterator on react

### ISSUE THREAD

**Issue by cquiroz** [ochrons/diode#17]
If I put `Circuit.connect` in an iterator I get an error from React of the form 

`Warning: Each child in an array or iterator should have a unique "key" prop.`

This happens even if my wrapped components have a key

I think this is because when doing a connect you endup with multiple instances of a <DiodeWrapper> component without a key

I checked the `connect` code and I think it should contain a call:

```scala
.buildU.withKey("mykey").apply()
```

but I'm not sure what's the best way to pass the key argument. If you have any suggestions I could produce a PR

**Comment by ochrons** [comment]
Yeah, this issue pops up quite frequently with React as variable number of children tend to end up in an array when using Scalajs-react. Basically the key would have to be passed as an optional parameter to `connect` to circumvent this.

Depending on your use case, you might also want to consider `connect`ing the whole sequence, instead of individual items. If your components have properly defined `shouldComponentUpdate` it will be fast.

**Comment by cquiroz** [comment]
Thanks a lot. Would there be any side effects of setting the key to js.undef in the default case?
