### ISSUE TITLE
Reusing dispatching functions with React

### ISSUE THREAD

**Issue by naksu** [ochrons/diode#5]
Is there any way to use reusable functions for dispatch calls, to avoid repeated rendering of buttons etc.? (https://github.com/japgolly/scalajs-react/blob/master/doc/PERFORMANCE.md)

Currently I've defined a singleton for the action functions, and passing that object for every component that needs to dispatch actions. This leaves the dispatcher in the ModelProxy unused.
```
case class Actions(dispatcher: Dispatcher) {
  val increase: ReusableFn0[Unit] = ReusableFn0(() => dispatcher(Increase(2)))
  val decrease: ReusableFn0[Unit] = ReusableFn0(() => dispatcher(Decrease(1)))
  val reset: ReusableFn0[Unit] = ReusableFn0(() => dispatcher(Reset))
}
```
```
  val actions = Actions(AppCircuit)

  val routerConfig: RouterConfig[Page] = RouterConfigDsl[Page].buildConfig { dsl =>
      ...
      | staticRoute(root, HomePage) ~> renderR { router =>
        AppCircuit.connect { model => model } { proxy =>
          HomeView.Component(HomeView.Props("Home", proxy, actions, router))
        } 
      }
      ...
```

And finally in the component:
```
  class Backend(scope: BackendScope[Props, Unit]) {
    def render(props: Props) = {
      <.div(
        <.p("Value = ", <.b(props.proxy.value.counter)),
        ButtonGroup.Component(
          Button(Button.Props(props.actions.increase), "Increase"),
          Button(Button.Props(props.actions.decrease), "Decrease"),
          Button(Button.Props(props.actions.reset), "Reset")))
    }
  }
```

(In case you are wondering where ReusableFn0, I defined a custom 0-arity ReusableFn. As such type does not exist in scalajs-react, I might be doing something wrong there.)

**Comment by ochrons** [comment]
Would you get the same result by just declaring the callbacks as `val`s in the `Backend` class?

```scala
  class Backend(scope: BackendScope[Props, Unit]) {
    val incCB = scope.props.flatMap(_.proxy.dispatch(Increase(2)))
    val decCB = scope.props.flatMap(_.proxy.dispatch(Decrease(1))) 
    val resetCB = scope.props.flatMap(_.proxy.dispatch(Reset)) 

    def render(props: Props) = {
      <.div(
        <.p("Value = ", <.b(props.proxy.value.counter)),
        ButtonGroup.Component(
          Button(Button.Props(incCB), "Increase"),
          Button(Button.Props(decCB), "Decrease"),
          Button(Button.Props(resetCB), "Reset")))
    }
  }
```

Also your `Button` would have to have `shouldComponentUpdate` defined for any of this to make any difference.

In general, you don't need the `Reusability` tricks with Diode, since the model is immutable and any change is automatically an indication to re-render. That's the whole point of the `connect` method :)

Of course you should not pass the whole model around to components, as that will trigger render on any change anywhere in the model. The passed model should be scoped correctly to avoid that.

**Comment by naksu** [comment]
Thanks, using callbacks that way does seem to work. I defined reusability in the Button component as 

```scala
implicit val functionReuse = Reusability.by_==[CallbackTo[Unit]]
```

Diode being inspired by Redux, I was following Redux's principle of having the connector only at the topmost component (http://rackt.org/redux/docs/basics/UsageWithReact.html: "Try to only do this for a top-level component, ..."). Earlier I was calling `connect` in the router. Based on your comments, I'm now passing my `AppCircuit` (actually just `trait ReactCircuit extends Circuit[RootModel] with diode.react.ReactConnector[RootModel]`) to the active top-level view.  The top-level view then connects sub-components to subset of the state. Does this make sense?

**Comment by ochrons** [comment]
Redux doesn't have fine-grained listener model, so it makes sense to have only the top components "connected" but with Diode it's a different situation. 

You should `wrap` components that do not actively need to be told about changes (many top-level components are like this, because they only contain other components) and then use `connect` on the next level components that do need to be notified when the model changes. This will minimize re-renderings when the model is updated.

For example from the SPA tutorial:
```scala
    (staticRoute(root, DashboardLoc) ~> renderR(ctl => SPACircuit.wrap(_.motd)(proxy => Dashboard(ctl, proxy)))
      | staticRoute("#todo", TodoLoc) ~> renderR(ctl => SPACircuit.connect(_.todos)(Todo(_)))
      ).notFound(redirectToPage(DashboardLoc)(Redirect.Replace))

  def layout(c: RouterCtl[Loc], r: Resolution[Loc]) = {
    <.div(
      // here we use plain Bootstrap class names as these are specific to the top level layout defined here
      <.nav(^.className := "navbar navbar-inverse navbar-fixed-top",
        <.div(^.className := "container",
          <.div(^.className := "navbar-header", <.span(^.className := "navbar-brand", "SPA Tutorial")),
          <.div(^.className := "collapse navbar-collapse",
            // connect menu to model, because it needs to update when the number of open todos changes
            SPACircuit.connect(_.todos.map(_.items.count(!_.completed)).toOption)(proxy => MainMenu(c, r.page, proxy))
          )
        )
      ),
      // currently active module is shown in this container
      <.div(^.className := "container", r.render())
    )
  }
```

It wraps the MOTD module as it's just a container, but uses `connect` for the Todos and the menu, as they need update notifications.

**Comment by ochrons** [comment]
Actually the SPA example has a problem with the menu `connect` since it uses a calculated value, which will always resolve in a new reference and therefore force re-rendering. It should just use `_.items` and do the counting in the component itself. This will be fixed in the next SPA release.

**Comment by naksu** [comment]
Thanks again. I now see that `wrap` vs `connect` is explained in the documentation. Sorry I didn't read the docs well enough. :) My code is much cleaner now, based on your suggestions.

Overall, I am very impressed by the quality of Diode, and how well you have thought it out. Thank you for contributing it.
